### ISSUE TITLE
[Bug]: bug title

### ISSUE THREAD

**Issue by qgallouedec** [qgallouedec/fake_repo_for_issue_form#5]
### 🐛 Bug

When using two keys that have different prefixes (tags) but the same key name, HumanOutputFormat will raise, complaining that the keys are duplicated.

### To Reproduce

```python
from stable_baselines3.common.logger import HumanOutputFormat

o = HumanOutputFormat(sys.stdout, max_length=50)
o.write({'key1/banana': 'value1', 'key2/banana': 'value2'}, {"key1/banana": None, "key2/banana": None})
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/Users/rocamonde/git/HumanCompatibleAI/imitation/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-ff13417a6e34>", line 2, in <module>
    o.write({'key1/banana': 'value1', 'key2/banana': 'value2'}, {"key1/banana": None, "key2/banana": None})
  File "/Users/rocamonde/git/HumanCompatibleAI/imitation/venv/lib/python3.9/site-packages/stable_baselines3/common/logger.py", line 183, in write
    raise ValueError(
ValueError: Key '   banana' truncated to '   banana' that already exists. Consider increasing `max_length`.
```

### System Info

OS: macOS-12.6-x86_64-i386-64bit Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
Python: 3.9.13
Stable-Baselines3: 1.7.0a0
PyTorch: 1.12.1
GPU Enabled: False
Numpy: 1.23.3
Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
This is a test.

**Comment by qgallouedec** [comment]
This is another test.

**Comment by qgallouedec** [comment]
Hello

**Comment by qgallouedec** [comment]
World
